### ISSUE TITLE
v0.2.20 Causing failures in `crx` pkg

### ISSUE THREAD

**Issue by erikmunson** [rzcoder/node-rsa#32]
After the update to 0.2.20, the `crx` package was made unusable (at least for my project), providing this error from `crx` itself:

```
Error: TypeError: undefined is not a function
  at jenkins-home/workspace/SignalsExtension-Master/node_modules/crx/src/crx.js:83:13
  at $$$internal$$tryCatch (jenkins-home/workspace/SignalsExtension-Master/node_modules/crx/node_modules/es6-promise/dist/es6-promise.js:304:16)
  at $$$internal$$invokeCallback (jenkins-home/workspace/SignalsExtension-Master/node_modules/crx/node_modules/es6-promise/dist/es6-promise.js:316:17)
  at jenkins-home/workspace/SignalsExtension-Master/node_modules/crx/node_modules/es6-promise/dist/es6-promise.js:874:13
  at $$asap$$flush (jenkins-home/workspace/SignalsExtension-Master/node_modules/crx/node_modules/es6-promise/dist/es6-promise.js:111:9)
  at process._tickCallback (node.js:419:13)
```

Hard-coding the `node-rsa` dependency in `crx` to *only* accept version 0.2.10 of `node-rsa` consistently fixes the issue.

[I have already posted this on CRX](https://github.com/oncletom/crx/issues/43), but I wanted to post an issue here to be sure it was noticed by both parties. Unsure yet whether this is because an API method was removed/changed without a major version bump, or because of something else less general.

**Comment by rzcoder** [comment]
This stack dont give me any info where in node-rsa problem might be.
If exception raising while loading PEM, problem might be in new regexp, but all my tests for import PEM is passing good. So, you can give me any example of PEM that causing error.

**Comment by erikmunson** [comment]
@rzcoder Thanks for your prompt response. I realize this stack isn't particularly helpful, and I'm currently working on getting a more detailed trace of what's going wrong. Will post more details as soon as I have them.

**Comment by rzcoder** [comment]
Uh, wait. I just found one bug. Try update node-rsa to 0.2.21.

**Comment by erikmunson** [comment]
@rzcoder Excellent, works great! Many thanks for jumping on this so quickly :+1:

**Comment by rzcoder** [comment]
You welcome.
